### ISSUE TITLE
"An error occured while communicating to the server." when clicking existing zones on new nsedit install

### ISSUE THREAD

**Issue by damianharouff** [tuxis-ie/nsedit#100]
I've recently upgraded an old existing PowerDNS installation to PowerDNS 4, and am replacing Poweradmin with nsedit.

I've got everything working in terms of being able to log in and view a list of zones, however, when I click on **_some_** zones, it returns "An error occurred while communicating to the server":
![ededazs1-049299fe95a2d195c2e4cd940e089a70](https://cloud.githubusercontent.com/assets/2953243/17531159/90276ebe-5e2f-11e6-9168-ec4e6678870f.png)

Every time I click on one of these zones that return the "An error..." message, I see the following in the HTTP server error log:

`[Tue Aug 09 14:33:06.792372 2016] [:error] [pid 13398] [client x.x.x.x:41590] PHP Fatal error:  Call to undefined function Exception() in /var/www/html/nsedit/includes/class/Zone.php on line 243, referer: http://ns1.redacted.com/nsedit/index.php
[Tue Aug 09 14:33:18.933587 2016] [:error] [pid 17214] [client x.x.x.x:41600] PHP Fatal error:  Call to undefined function Exception() in /var/www/html/nsedit/includes/class/Zone.php on line 243, referer: http://ns1.redacted.com/nsedit/index.php
[Tue Aug 09 14:33:26.489658 2016] [:error] [pid 17287] [client x.x.x.x:41602] PHP Fatal error:  Call to undefined function Exception() in /var/www/html/nsedit/includes/class/Zone.php on line 243, referer: http://ns1.redacted.com/nsedit/index.php
[Tue Aug 09 14:34:35.041491 2016] [:error] [pid 13420] [client x.x.x.x:41632] PHP Fatal error:  Call to undefined function Exception() in /var/www/html/nsedit/includes/class/Zone.php on line 243, referer: http://ns1.redacted.com/nsedit/index.php
[Tue Aug 09 14:35:03.377555 2016] [:error] [pid 13398] [client x.x.x.x:41642] PHP Fatal error:  Call to undefined function Exception() in /var/www/html/nsedit/includes/class/Zone.php on line 243, referer: http://ns1.redacted.com/nsedit/index.php
[Tue Aug 09 14:35:24.824011 2016] [:error] [pid 13444] [client x.x.x.x:41644] PHP Fatal error:  Call to undefined function Exception() in /var/www/html/nsedit/includes/class/Zone.php on line 243, referer: http://ns1.redacted.com/nsedit/index.php
`

OK so if we take a look at line 243 I see that it's part of this block of code:
 public function addRecord($content, $disabled = FALSE, $setptr = FALSE) {
        foreach ($this->records as $record) {
            if ($record->content == $content) {
                throw Exception("Record already exists");
            }
        }
        $record = new Record($content, $disabled, $setptr);
        array_push($this->records, $record);
    }

Line 243 is "throw Exception"... alright, I can see that this needs to be "throw new Exception....". I fix this, and now I get the following notice:
![c4kp7nk6-e6f143d47283c06337e9842b3124924f](https://cloud.githubusercontent.com/assets/2953243/17531343/4e295918-5e30-11e6-94c3-93656c7375e1.png)

I'd like to reiterate that this is an existing zone with data already in it, and it seems to affect only some of the zones. Other zones seem to work without issue.

Let me know what more data I can provide to help troubleshoot.

**Comment by tuxis-ie** [comment]
Grmbl. Can it be that there are actually duplicate records within the same rrset in those zones?

**Comment by damianharouff** [comment]
Yes, that does seem to be the issue... I deleted duplicates and it seems to load now. I appreciate the pointer on that.
