### ISSUE TITLE
"An error occured while communicating to the server." on new install

### ISSUE THREAD

**Issue by mikepop** [tuxis-ie/nsedit#103]
Hi, I got that error after install nsedit. I've checked api works, 8081 is working, pdns.users.sqlite3 exists and it's writeble and cannot find any useful info on any log. Is there any way to debug it? Thanks.

Regards

**Comment by tuxis-ie** [comment]
Which versions of nsedit and powerdns?

**Comment by mikepop** [comment]
4.0.1 and I gues 1.0 I've just git clone https://github.com/tuxis-ie/nsedit.git like 6 or 7 hours ago.

**Comment by tuxis-ie** [comment]
Nothing in your Apache error log?

**Comment by mikepop** [comment]
Nginx, nothing in error log.
![captura de pantalla 2016-08-17 a las 20 57 09](https://cloud.githubusercontent.com/assets/1940173/17749309/65632af8-64bd-11e6-9497-93282eb350f7.png)

**Comment by tuxis-ie** [comment]
Nginx? So php-fpm? Error logging fromphp-from is silent? Do you have Curl installed and enabled?

**Comment by mikepop** [comment]
Yes, nothing also in php-fpm error log, curl-7.29.0-25.el7.centos.x86_64 is installed.

**Comment by mikepop** [comment]
[root@ns1 test]# php -v
PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
[root@ns1 test]# php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

**Comment by mikepop** [comment]
It was indeed some php issue, I've upgraded to php 7 and is working now.
