### ISSUE TITLE
Clearing of logs

### ISSUE THREAD

**Issue by richard-underwood** [tuxis-ie/nsedit#107]
Hi - I need to make sure that logs can't be cleared too easily. I was thinking of implementing two new options (allowclearlogs allowrotatelogs) and then have a rotate logs button which would export the json to a file in a logs directory on the server. There could be a drop-down on the logs page to view rotated logs. Rotated log files could then be cleared up with standard logrotate (etc.) or backed up for compliance.

I'm happy to make the changes for this, but is this something which fits in with the roadmap, or would it conflict with other plans?

**Comment by tuxis-ie** [comment]
Great idea!

Maybe directly implement a cron-like thingy? So a rotate could be automatically done upon a hit?

**Comment by tuxis-ie** [comment]
Merged!
