### ISSUE TITLE
Warning: SQLite3Stmt::execute() [sqlite3stmt.execute]: Unable to execute statement: constraint failed in .../nsedit/includes/misc.inc.php on line 297

### ISSUE THREAD

**Issue by jasonhorton** [tuxis-ie/nsedit#109]
Brand new setup on Centos 6, PHP 5.3.3

When I disable logging in config.inc.php, we get past this error, but then are hit with "An error occured while communicating to the server."

**Comment by richard-underwood** [comment]
I've not tried with PHP 5.3, but there's at least one issue which will prevent 5.4 from working (and therefore also 5.3). 

You could try the diff linked below which addresses it, but there may be other issues with 5.3 - you would probably do better installing CentOS 7 which has PHP 5.4 or using a repository like IUS (https://ius.io/) and installing 5.6.

https://github.com/richard-underwood/nsedit/commit/2cb95a695932c3c5e34ac1a7e6a3b8a6be80d848

**Comment by tuxis-ie** [comment]
Logging issue is fixed in  #105 (Which is now merged). The second issue, could it be related to 2cb95a695932c3c5e34ac1a7e6a3b8a6be80d848 ?

**Comment by tuxis-ie** [comment]
This was probably the issue with #103 as well..

**Comment by jasonhorton** [comment]
These two fixed the issue so far. Thanks!
