### ISSUE TITLE
Search returns 500 API error

### ISSUE THREAD

**Issue by ruben-herold** [tuxis-ie/nsedit#119]
hi,

If I try the search I ever got an 500 API error.

**Comment by tuxis-ie** [comment]
Version? Php-error logs? pdns Error logs? 

A bit more information is useful. My primary reaction to such an issue is 'Ok, thanks for the information' and then just close the bug.

**Comment by skf82** [comment]
I had the same problem after updating to PowerDNS 4. In my case it was that some zones actually contained bad data which threw an 500 API error when i searched for those zones. I was able to fix the issue by identifying the bad zones and deleting the records manually in mysql

**Comment by richard-underwood** [comment]
I had a similar problem after importing a zone from bind - there were duplicate records in the zone which needed thinning out. It was a powerdns problem, not nsedit.

**Comment by tuxis-ie** [comment]
Ok. So mainly, the errorhandling needs to be better.

**Comment by skf82** [comment]
I guess it might be related to this?
https://github.com/PowerDNS/pdns/pull/4195

**Comment by tuxis-ie** [comment]
@skf82 No. This issue is about search, not about importing. But thank you for pointing out that issue, it is something we are using. :)

**Comment by telefax** [comment]
I just did a bulk import to pdns mysql via zone2sql and got the same problem when searching for a specific term in nsedit ui.

The httpd instance that run nsedit had nothing in its error logs.
But if you check the powerdns web statistics page (port 8081) you would see something like:


> HTTP ISE for "/api/v1/servers/localhost/zones/some.zone.": STL Exception: Parsing record content (try 'pdnsutil check-zone'): Data field in DNS should start with quote (") at position 2 of '""v=spf1 mx ip4:1.1.1.1,2.2.2.2 -all""'	

So, problem in this case was that I had a TXT record which was surrounded by extra quotes (probably had never worked at the place where the zones originates from).
Quick fix mysql query was to locate the records and then remove the extra quotes:

`SELECT * FROM `powerdns_db`.records where content like '""%""';`

So again, not an nsedit problem it self, but it's having a hard time interpreting syntax errors in zones :)

**Comment by tuxis-ie** [comment]
Yes, we have to find out if we get these messages from PDNS. I don't know yet.

**Comment by tuxis-ie** [comment]
I've created issue #128 for these issues.
