### ISSUE TITLE
Deleting a user doesn't work

### ISSUE THREAD

**Issue by richard-underwood** [tuxis-ie/nsedit#122]
While looking at groups, I noticed that deleting a user doesn't work. The jtable is set to use the username as the key, not the id, but the delete sql is by id.

I'm going to propose a patch which changes the key on the user jtable to be the id field which matches the other jtables and update misc to match before going forward with the groups.

**Comment by HLFH** [comment]
Related to https://github.com/tuxis-ie/nsedit/pull/123

**Comment by HLFH** [comment]
It works. Thanks. You can close this issue. @tuxis-ie @richard-underwood
