### ISSUE TITLE
Session expiry problem

### ISSUE THREAD

**Issue by richard-underwood** [tuxis-ie/nsedit#126]
The session expires after exactly half an hour, whether it's been active or not. It would make sense to reduce the timeout and instead extend the session each time the session is validated by a request.

It looks like this is a limitation in the PHP session functions. The best solution appears to be to set a long-lasting cookie (perhaps a session cookie with no lifetime) and then store the expiry within the session.

http://php.net/manual/en/function.session-set-cookie-params.php#12811

**Comment by bjoe2k4** [comment]
Just set a `$secret` in `config.inc.php` (commented out by default) and there will be a checkbox below the login that allows you to stay logged in for a month via an autologin cookie. Works well for me.
