### ISSUE TITLE
After upgrade to latest nsedit and powerdns (v4) API Error 500

### ISSUE THREAD

**Issue by harkx** [tuxis-ie/nsedit#132]
After upgrading (and correcting some records because of missing quotes etc..) I keep getting "API Error 500: Internal Server Error", the error that keeps returning in the pdns error (log/webserver) is;

> HTTP ISE for "/api/v1/servers/localhost/zones": STL Exception: stou

Any idea what I'm missing here? I "think" this is a PowerDNS issue but can't figure out what's wrong so it might still be config or something.

![image](https://cloud.githubusercontent.com/assets/7738282/19908582/45e5ac0c-a084-11e6-81f4-9c360abc5ba2.png)

**Comment by tuxis-ie** [comment]
What does pdnsutil check-all-zones say? Usually this is because of errors in a zone, which makes the API barf.

**Comment by harkx** [comment]
```
ns1 /etc/powerdns # pdnsutil list-all-zones -v
Nov 01 23:07:22 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Error: stou
```

Forgive me for opening the ticket too soon, but indeed, an incorrect SOA record caused this. after fixing that, the list-all-zones works !

Sorry for that but thanks! :) Now the api works as it should.
