### ISSUE TITLE
In zones overview, serial shows 0 instead of correct serial number

### ISSUE THREAD

**Issue by harkx** [tuxis-ie/nsedit#133]
Small display issue with the overview zones screen, it does not show the serial in the overview:

![image](https://cloud.githubusercontent.com/assets/7738282/19919449/2885256c-a0d3-11e6-8e35-700787b5ad14.png)

When "searching" however it does show the serial correctly:

![image](https://cloud.githubusercontent.com/assets/7738282/19919490/73e580ec-a0d3-11e6-8eec-124abd939d11.png)

**Comment by tuxis-ie** [comment]
Is this for all your zones or just one?

**Comment by harkx** [comment]
It's for all zones, on my main overview they all show 0 as serial. When searching however it shows correctly.

![image](https://cloud.githubusercontent.com/assets/7738282/19920621/223fa6ee-a0da-11e6-872c-ea2ab871a825.png)

**Comment by tuxis-ie** [comment]
Are you able to query the pdns API directly? I have the feeling this is a pdns issue.

**Comment by harkx** [comment]
Yeah, sure, for the rest it's working, and it does show the serial correctly when I search a domain in nsedit,  just not in the default overview screen.

If you want me to do a specific query, let me know, I'd be happy to test.

**Comment by tuxis-ie** [comment]
Sorry that this took me so long. 

Can you show a SOA-record for which the serial is displayed incorrectly?

**Comment by harkx** [comment]
Here's an example and indeed I think you're right, the SOA record is messed up:

![image](https://cloud.githubusercontent.com/assets/7738282/20236391/1234c9d2-a8b4-11e6-9cda-f5fb5026c7f8.png)

according to pdnsutil check-zone:

![image](https://cloud.githubusercontent.com/assets/7738282/20236413/9db913be-a8b4-11e6-8ac2-814d72917d37.png)

Now to find out what's wrong.. I always created zones like this, also DNS queries don't error.

**Comment by harkx** [comment]
I must've checked the wrong zone last time with pdnsutil check-zone because when I do that for my domains, it gives correct results. Sorry for the mistake.

![image](https://cloud.githubusercontent.com/assets/7738282/20258349/86b321b8-aa4f-11e6-9ade-acb572ada40a.png)


But the problem remains in the view though.. when searching a domain the results show the domain and the correct serial. When just in the default via (no search) it displays 0.

**Comment by krombel** [comment]
I found out, that the powerdns-API produced the wrong serial.

I got following response when fetching the API directly from powerdns:
```
curl -H "X-API-Key: MySecretAPI-Key" localhost:4321/api/v1/servers/localhost/zones | python -m json.tool
[
    {
        "account": "test",
        "dnssec": false,
        "id": "mydomain.tld.",
        "kind": "Master",
        "last_check": 0,
        "masters": [],
        "name": "mydomain.tld.",
        "notified_serial": 0,
        "serial": 0,
        "url": "api/v1/servers/localhost/zones/mydomain.tld."
    }
]
```
So this issue has to be fixed upstream

**Comment by krombel** [comment]
And it seems to be an open issue already
PowerDNS/pdns#4328
