### ISSUE TITLE
Please add support for recordtype ALIAS

### ISSUE THREAD

**Issue by ruben-herold** [tuxis-ie/nsedit#138]
hi,

please add support for the recordtype ALIAS:

https://doc.powerdns.com/md/types/

**Comment by tuxis-ie** [comment]
We could do so, but if I read the docs it should not be a type that is available by default. What do you think?

**Comment by ruben-herold** [comment]
If you use it and it is not activate nothing happed as far as I have tested it. 
or make it configurable via configuration to make Record Types available.

Especially  the ALIAS record type would be very helpfull:
https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/

**Comment by micuenta** [comment]
+1 to support the recordtype ALIAS

**Comment by Nosxxx** [comment]
+1 
I like alias records :)
