### ISSUE TITLE
Cannot Add Zone

### ISSUE THREAD

**Issue by sgel83** [tuxis-ie/nsedit#139]
I just installed nsedit and am trying to use it with pdns 4.0.3.  Everytime I try to add a zone I am getting an error.

API Error 422: DNS name 'test.local' is not canonical

Is this something with powerdns or nsedit?

CentOS 6.8
pdns-4.0.3-1.el6.MIND.x86_64
pdns-backend-mysql-4.0.3-1.el6.MIND.x86_64

       0x0020:  8018 0200 ffe3 0000 0101 080a 0093 06bb  ................
        0x0030:  0093 06bb 504f 5354 202f 6170 692f 7631  ....POST./api/v1
        0x0040:  2f73 6572 7665 7273 2f6c 6f63 616c 686f  /servers/localho
        0x0050:  7374 2f7a 6f6e 6573 2048 5454 502f 312e  st/zones.HTTP/1.
        0x0060:  310d 0a48 6f73 743a 2031 3237 2e30 2e30  1..Host:.127.0.0
        0x0070:  2e31 3a38 3038 310d 0a58 2d41 5049 2d4b  .1:8081..X-API-K
        0x0080:  6579 3a20 3463 3363 6461 6639 2d64 3631  ey:.4c3cdaf9-d61
        0x0090:  392d 3461 3935 2d38 3034 622d 6333 3766  9-4a95-804b-c37f
        0x00a0:  3263 3761 3764 3235 0d0a 4163 6365 7074  2c7a7d25..Accept
        0x00b0:  3a20 6170 706c 6963 6174 696f 6e2f 6a73  :.application/js
        0x00c0:  6f6e 0d0a 436f 6e74 656e 742d 4c65 6e67  on..Content-Leng
        0x00d0:  7468 3a20 3232 370d 0a43 6f6e 7465 6e74  th:.227..Content
        0x00e0:  2d54 7970 653a 2061 7070 6c69 6361 7469  -Type:.applicati
        0x00f0:  6f6e 2f78 2d77 7777 2d66 6f72 6d2d 7572  on/x-www-form-ur
        0x0100:  6c65 6e63 6f64 6564 0d0a 0d0a 7b22 6163  lencoded....{"ac
        0x0110:  636f 756e 7422 3a22 222c 226e 616d 6573  count":"","names
        0x0120:  6572 7665 7273 223a 5b22 756e 636f 6e66  ervers":["unconf
        0x0130:  6967 7572 6564 2e70 7269 6d61 7279 6e73  igured.primaryns
        0x0140:  2e22 2c22 756e 636f 6e66 6967 7572 6564  .","unconfigured
        0x0150:  2e73 6563 6f6e 6461 7279 6e73 2e22 5d2c  .secondaryns."],
        0x0160:  226b 696e 6422 3a22 4d61 7374 6572 222c  "kind":"Master",
        0x0170:  226e 616d 6522 3a22 7465 7374 2e6c 6f63  "name":"test.loc
        0x0180:  616c 222c 2273 6f61 5f65 6469 7422 3a22  al","soa_edit":"
        0x0190:  494e 4345 5054 494f 4e2d 494e 4352 454d  INCEPTION-INCREM
        0x01a0:  454e 5422 2c22 736f 615f 6564 6974 5f61  ENT","soa_edit_a
        0x01b0:  7069 223a 2249 4e43 4550 5449 4f4e 2d49  pi":"INCEPTION-I
        0x01c0:  4e43 5245 4d45 4e54 222c 2264 6e73 7365  NCREMENT","dnsse
        0x01d0:  6322 3a22 222c 226d 6173 7465 7273 223a  c":"","masters":
        0x01e0:  5b5d 2c22 7365 7269 616c 223a 2222 7d    [],"serial":""}

        0x0030:  0093 06bb 4854 5450 2f31 2e31 2034 3232  ....HTTP/1.1.422
        0x0040:  2055 6e6b 6e6f 776e 2053 7461 7475 730d  .Unknown.Status.
        0x0050:  0a41 6363 6573 732d 436f 6e74 726f 6c2d  .Access-Control-
        0x0060:  416c 6c6f 772d 4f72 6967 696e 3a20 2a0d  Allow-Origin:.*.
        0x0070:  0a43 6f6e 6e65 6374 696f 6e3a 2063 6c6f  .Connection:.clo
        0x0080:  7365 0d0a 436f 6e74 656e 742d 4c65 6e67  se..Content-Leng
        0x0090:  7468 3a20 3531 0d0a 436f 6e74 656e 742d  th:.51..Content-
        0x00a0:  5365 6375 7269 7479 2d50 6f6c 6963 793a  Security-Policy:
        0x00b0:  2064 6566 6175 6c74 2d73 7263 2027 7365  .default-src.'se
        0x00c0:  6c66 273b 2073 7479 6c65 2d73 7263 2027  lf';.style-src.'
        0x00d0:  7365 6c66 2720 2775 6e73 6166 652d 696e  self'.'unsafe-in
        0x00e0:  6c69 6e65 270d 0a43 6f6e 7465 6e74 2d54  line'..Content-T
        0x00f0:  7970 653a 2061 7070 6c69 6361 7469 6f6e  ype:.application
        0x0100:  2f6a 736f 6e0d 0a53 6572 7665 723a 2050  /json..Server:.P
        0x0110:  6f77 6572 444e 532f 342e 302e 330d 0a58  owerDNS/4.0.3..X
        0x0120:  2d43 6f6e 7465 6e74 2d54 7970 652d 4f70  -Content-Type-Op
        0x0130:  7469 6f6e 733a 206e 6f73 6e69 6666 0d0a  tions:.nosniff..
        0x0140:  582d 4672 616d 652d 4f70 7469 6f6e 733a  X-Frame-Options:
        0x0150:  2064 656e 790d 0a58 2d50 6572 6d69 7474  .deny..X-Permitt
        0x0160:  6564 2d43 726f 7373 2d44 6f6d 6169 6e2d  ed-Cross-Domain-
        0x0170:  506f 6c69 6369 6573 3a20 6e6f 6e65 0d0a  Policies:.none..
        0x0180:  582d 5873 732d 5072 6f74 6563 7469 6f6e  X-Xss-Protection
        0x0190:  3a20 313b 206d 6f64 653d 626c 6f63 6b0d  :.1;.mode=block.
        0x01a0:  0a0d 0a7b 2265 7272 6f72 223a 2022 444e  ...{"error":."DN
        0x01b0:  5320 4e61 6d65 2027 7465 7374 2e6c 6f63  S.Name.'test.loc
        0x01c0:  616c 2720 6973 206e 6f74 2063 616e 6f6e  al'.is.not.canon
        0x01d0:  6963 616c 227d                           ical"}

**Comment by tuxis-ie** [comment]
Try adding a . at the end of the zone, making the name 'Canonical'.
