### ISSUE TITLE
Add support for CAA record

### ISSUE THREAD

**Issue by wiza** [tuxis-ie/nsedit#141]
Please add support for CAA record per RFC 6844, supported in powerdns 4.0.0.

https://doc.powerdns.com/md/types/

**Comment by righter83** [comment]
DIFF index.php
`136a137
> 			<option value="CAA">CAA</option>
625a627
> 										'CAA': 'CAA',
1200d1201
< 
`

**Comment by tuxis-ie** [comment]
@righter83 That is too fast. What kind of value is in CAA ? Should it be quoted, treated like a TXT record?

**Comment by righter83** [comment]
@tuxis-ie 
Now it's a new special record:
https://sslmate.com/labs/caa/

It's not quoted, but it has quotes inside the record.value
example.com.	IN	CAA	0 issue "letsencrypt.org"

**Comment by HLFH** [comment]
Following this discussion, for Let's Encrypt, it is recommended to use CAA with Critical Flag enabled: https://community.letsencrypt.org/t/caa-setup-for-lets-encrypt/9893

> example.com. CAA 128 issue "letsencrypt.org"

Since NSEditis the best WebUI for PowerDNS, it would be great to support CAA RRs.
