### ISSUE TITLE
Error in processing template records if name is ''

### ISSUE THREAD

**Issue by bajizs** [tuxis-ie/nsedit#142]
If you have empty name for some template records (for example MX record), get an API error of not canonical name.

can be solved withthis lines in zones .php (replace lines 296-298 with next lines):
            foreach ($template['records'] as $record) {
                $name = $record['name'];
                if ('' == $name) {
                    $name = $zone->name;
                } elseif (string_ends_with($name, '.')) {
                    $name = substr($name, 0, -1);
                    if (!string_ends_with($name, $zone->name)) {
                        jtable_respond(null, 'error', "Name $name not in zone ".$zone->name);
                    }
                } else if (!string_ends_with($name, $zone->name)) {
                    $name = $name . '.' . $zone->name;
                }
                $zone->addRecord($name, $record['type'], $record['content']);
            }

**Comment by tuxis-ie** [comment]
This works for me?

```
        array(
            'name'      => '',
            'type'      => 'MX',
            'content'   => '10 connect.tuxis.nl.'),
        array(
            'name'      => '',
            'type'      => 'MX',
            'content'   => '20 fallback.tuxis.nl.'),
```

**Comment by bajizs** [comment]
On relase v1.1?

**Comment by tuxis-ie** [comment]
Yes, always worked.
