### ISSUE TITLE
Error 404 when trying to add a simple A record.

### ISSUE THREAD

**Issue by rdoerr01** [tuxis-ie/nsedit#145]
I've been struggling to get NSEDIT working with PowerDNS.  O I have PowerDNS working fine and can do any API call to it.  NSEDIT GUI comes up and I can create the Domain, but it gives an error 404 and creates it anyway.  But if you try and create an A record, you get the 404 and nothing is created in the DB.  You get this in the PowerDNS API logs.
```
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 HTTP: Handling request "/api"
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 HTTP: Result for "/api": 200, body length: 34
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 HTTP: Handling request "/api/v1/servers/localhost/zones/ttlab.com."
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 HTTP: Result for "/api/v1/servers/localhost/zones/ttlab.com.": 200, body length: 711
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 HTTP: Handling request "/apiv1serverslocalhostzonesttlab.com."
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 HTTP: No route found for "/apiv1serverslocalhostzonesttlab.com."
Apr 27 18:22:17 powerdns pdns_server: Apr 27 18:22:17 HTTP: Error result for "/apiv1serverslocalhostzonesttlab.com.": 404
```
I'm using PowerDNS
Installed:
  pdns.x86_64 0:4.0.3-1pdns.el7

NSEDIT using git on the Master branch.  I've tried checkout of Tag 1.0 and 1.1, but checking out the master branch worked better, but still can't get around the 404.

**Comment by phelset** [comment]
See comments on commit https://github.com/tuxis-ie/nsedit/commit/4d4e536d52d93cf41b25bbfe530775dd10c51df9.
Quickfix: comment out line 94 in includes/class/ApiHandler.php
