### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by sebastiaanvroom** [tuxis-ie/nsedit#147]
Hi! Stupidly enough, I locked myself out. I tried reïnstalling but I cannot seem to find the user database that is supposed to be located at /etc/pdns.users.sqlite3. Is it possible to reset the admin password in any way?

**Comment by tuxis-ie** [comment]
Its in ```../etc/``` , not ```/etc```

**Comment by sebastiaanvroom** [comment]
My bad :\ thanks
