### ISSUE TITLE
can you edit zone meta data?

### ISSUE THREAD

**Issue by fsantiago07044** [tuxis-ie/nsedit#149]
can you edit zone meta data with this tool? doesn't seem so...unless i'm missing something.

pdns version 4.0.3-1pdns.el7

**Comment by tuxis-ie** [comment]
What do you mean by meta data?

**Comment by fsantiago07044** [comment]
when you run:

pdnsutil show-zone <domain>

your receive:

This is a Master zone
Last SOA serial number we notified: 1495065601 == 1495065601 (serial in the database)
Zone is not actively secured
Metadata items:
        ALLOW-AXFR-FROM AUTO-NS
No keys for zone '<domain>'.

the metadata items i've set by hand using pdnsutil. that's what i mean.

**Comment by fsantiago07044** [comment]
for example:

pdnsutil set-meta "domain" ALLOW-AXFR-FROM AUTO-NS

**Comment by fsantiago07044** [comment]
unrelated to this but i also do not see how to implement dnssec thru your interface? it shows current values but where to edit / implement it?

**Comment by righter83** [comment]
To create or edit you have to use the pdns server tools.
I think the problem is, that this function is not implemented by the powerdns API yet...

**Comment by fsantiago07044** [comment]
June 20, 2017 8:30 AM, "righter83" <notifications@github.com> wrote:

> To create or edit you have to use the pdns server tools.
> I think the problem is, that this function is not implemented by the powerdns API yet...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

thank you. i came to realize that was likely in fact the case (lack of api implementation). have a good day and close my tickets please at your leisure. 

--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC
