### ISSUE TITLE
Add support for CAA records

### ISSUE THREAD

**Issue by kruisdraad** [tuxis-ie/nsedit#154]
To allow adding of CAA records. Is supported in powerdns since 4.0.0

**Comment by mikedamm** [comment]
As a workaround, you can import a zonefile on a newly created zone that contains CAA records.

**Comment by kruisdraad** [comment]
I can also insert it manually into the database after, but then the zone is not really managed by nsedit anymore ;)

**Comment by tuxis-ie** [comment]
https://github.com/tuxis-ie/nsedit/commit/0e63757d19b88cfe5b0f4364f1852af40b88454c

**Comment by fsantiago07044** [comment]
am i missing something? my nsedit interface allows me to edit/manage caa records. i also have them in a template as well. ???
