### ISSUE TITLE
Feature Request: append . on new zones to make name canonical

### ISSUE THREAD

**Issue by chrino** [tuxis-ie/nsedit#158]
Ref. https://github.com/tuxis-ie/nsedit/issues/139 Can you please automatically append the last . to make new zones canonical. It is very cumbersome to have to remember the last dot.

**Comment by tuxis-ie** [comment]
This is a DNS product. There are more places where you need to add the trailing dot knowingly. But for consistency reasons, nsedit will not append it automagically.
