### ISSUE TITLE
notify pdns after zone update

### ISSUE THREAD

**Issue by Rico29** [tuxis-ie/nsedit#165]
Possibility to enable notification via API when a change is made on a zone

**Comment by tuxis-ie** [comment]
Please explain?

**Comment by Rico29** [comment]
Hello, tuxis-ie
Sorry, I want to create a pull request with changes I made...

I added a flag "notifyafterupdate" in config.inc.php. when this flag is set to true, then a notify is sent to slaves via the API : 
https://docs.powerdns.com/authoritative/http-api/zone.html#put--servers-server_id-zones-zone_id-notify

Just need to pull-request it

**Comment by HLFH** [comment]
Send a DNS NOTIFY to all slaves.
It seems I have the issue with my slave that does not get the `notify` after DNS updates via nsedit.
@tuxis-ie Shouldn't this https://github.com/tuxis-ie/nsedit/pull/166 be merged?
