### ISSUE TITLE
Can´t create database

### ISSUE THREAD

**Issue by weidnerd** [tuxis-ie/nsedit#170]
`[Mon Apr 02 21:16:09.370183 2018] [:error] [pid 22159] [client x.x.x.x:54594] PHP Fatal error:  Uncaught Exception: Unable to open database: unable to open database file in /var/www/html/nsed
it/includes/misc.inc.php:64\nStack trace:\n#0 /var/www/html/nsedit/includes/misc.inc.php(64): SQLite3->__construct('/etc/pdns.users...', 6)\n#1 /var/www/html/nsedit/includes/session.inc.php(4): inclu
de_once('/var/www/html/n...')\n#2 /var/www/html/nsedit/index.php(4): include_once('/var/www/html/n...')\n#3 {main}\n  thrown in /var/www/html/nsedit/includes/misc.inc.php on line 64`

what are the conditions that the database can be created?

**Comment by tuxis-ie** [comment]
Not much. But writing permissions for the web server users are. It looks like you want it to write to /etc/ which is probably not writable for the webserver user.
