### ISSUE TITLE
SMIMEA Record

### ISSUE THREAD

**Issue by weidnerd** [tuxis-ie/nsedit#174]
Hello!

Is there a plan to support the SMIMEA DNS record in NSEDIT?

regards

Daniel

**Comment by weidnerd** [comment]
I changed the index.php. The following error occurs:

![2018-08-22 16_46_14-nsedit](https://user-images.githubusercontent.com/29693572/44470852-01467780-a62b-11e8-993f-c8025c675753.png)

Do I need to make any changes to NSEDIT or PowerDNS?

**Comment by tuxis-ie** [comment]
This is an error coming from powerdns, not Nsedit.
