### ISSUE TITLE
404

### ISSUE THREAD

**Issue by BoomerB** [tuxis-ie/nsedit#178]
Hi,

I installed nsedit on Ubuntu 18.04 with Apache and php-fpm

I did:
git clone https://github.com/tuxis-ie/nsedit.git
cd nsedit/
git checkout tags/v1.1

I created a new domain. Now I wan to edit the SOA record and when I click Save I get an 404 error

PowerDNS logs show the following:

Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Handling request "/api"
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Result for "/api": 200, body length: 34
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Handling request "/api/v1/servers/localhost/zones/ltq.lab."
Jun 20 22:41:02 pdnsauth pdns_server[2917]: gpgsql Connection successful. Connected to database '' on '/run/postgresql'.
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Result for "/api/v1/servers/localhost/zones/ltq.lab.": 200, body length: 749
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Handling request "/api"
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Result for "/api": 200, body length: 34
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Handling request "/api/v1/api/v1/servers/localhost/zones/ltq.lab."
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: No route found for "/api/v1/api/v1/servers/localhost/zones/ltq.lab."
Jun 20 22:41:02 pdnsauth pdns_server[2917]: HTTP: Error result for "/api/v1/api/v1/servers/localhost/zones/ltq.lab.": 404

it looks like the prefix was applied twice

**Comment by dnshs** [comment]
In includes/class/PdnsApi.php

Remove localhost from 

            $api->url = '/localhost/zones';

**Comment by colbin8r** [comment]
+1
