### ISSUE TITLE
Invalid record ID

### ISSUE THREAD

**Issue by jpmens** [tuxis-ie/nsedit#18]
Edit A record. Change TTL. Hit Save.

![jmbp-1332](https://cloud.githubusercontent.com/assets/60706/5876685/762f7f88-a319-11e4-8c43-d9b66cc02d56.png)

**Comment by tuxis-ie** [comment]
I can't reproduce this.

**Comment by jpmens** [comment]
Also when hitting "delete" on a single RR:

![jmbp-1334](https://cloud.githubusercontent.com/assets/60706/5876940/cfc4835c-a31b-11e4-8a37-84ee89177483.png)

**Comment by jpmens** [comment]
If you can't reproduce this, it really means @habbie is at fault ;-)

**Comment by jpmens** [comment]
To make sure I'm using a zone created via API, I created a new zone, but I get the "invalid record id" message when trying to remove a record also.

**Comment by tuxis-ie** [comment]
This is fixed in PR #24

**Comment by jpmens** [comment]
Confirmed working, thanks!
