### ISSUE TITLE
Save/export zone does not work in most browsers

### ISSUE THREAD

**Issue by jpmens** [tuxis-ie/nsedit#20]
1. Click "export zone" 
2. Press browser's "back" button.

![jmbp-1333](https://cloud.githubusercontent.com/assets/60706/5876924/a0dc1b68-a31b-11e4-942a-aeedb19be181.png)

**Comment by tuxis-ie** [comment]
The save-zone button should cause a download. It does not submit anything. However, loggin in does submit stuff. So the dialog you're seeing is about the login-form.

**Comment by jpmens** [comment]
The save-zone button doesn't cause a download, at least not here.

**Comment by jpmens** [comment]
Confirm working in Chrome.
