### ISSUE TITLE
Add domains.account to new zone

### ISSUE THREAD

**Issue by jpmens** [tuxis-ie/nsedit#25]
The PowerDNS API [now exposes domains.account](https://github.com/PowerDNS/pdns/issues/2188) via the API. It would be nice if nsedit would allow this to be set on _Add new zone_ and edited on _Edit zone_.

**Comment by tuxis-ie** [comment]
What content would you expect here? If I understand #powerdns correctly, this will (or might) be overwritten by the receiving nameserver if the sender is a supermaster..

**Comment by jpmens** [comment]
If supermaster is in operation that would probably happen, yes, but no otherwise I think.

What I'd like to be able to add to `account` is an otherwise unchecked string of length <= `varchar(40)`.

**Comment by tuxis-ie** [comment]
Woulnd't that be redundant with 'Owner' ? Or do you want to see the owner in the Pdns database?

**Comment by jpmens** [comment]
I assume you mean nsedit's "owner"? That's not visible through the PowerDNS API is it? :)

I need a blob (however small) of info which an admin can edit and which is returned via the API

**Comment by tuxis-ie** [comment]
Running 3.4.2 I don't see this exposed. As soon as this becomes available in a release, I'll have a look at it (shouldn't be too difficult to implement).
