### ISSUE TITLE
Google Themes and https

### ISSUE THREAD

**Issue by piwats** [tuxis-ie/nsedit#26]
Hello,

I noticed that nsedit is loading some themes from google, which leads to some warnings on my browser when nsedit is accessed via https.

Would it be possible, from the standpoint of security considerations to add those themes directly to nsedit instead loding them from a 3rd-party website?

**Comment by tuxis-ie** [comment]
The calls are done by https://github.com/jquery/jquery-ui, which is automatically included from @jquery's github repo. For some reason they feel it's better to point to http:// instead of // . 

This should be pointed to them (I stronly agree with you, BTW)

**Comment by HLFH** [comment]
Related to `jtable`. Fixed. https://github.com/hikalkan/jtable/issues/1434

**Comment by tuxis-ie** [comment]
You can 'fix' this by doing in the root of nsedit checkout:
```
cd jtable
git pull origin master
```

This will update you local jtable instance to the lastest version which includes https://github.com/hikalkan/jtable/pull/1888

I'll fix the version that nsedit ships in the submodule way (Just after I found out how to do that ;))
