### ISSUE TITLE
Move menu/ appearance

### ISSUE THREAD

**Issue by piwats** [tuxis-ie/nsedit#27]
Hello,

I'm using/testing nsedit for a week now and I noticed how strange the menu which consists at this time only of 3 menu entries looks like.

Wouldn't it be nicer if the three menu items could move in a horizontal bar on top of the nsedit view? Also it might be useful if this bar could be fixed during scrolling.

The other thing I noticed about nsedit: DNS entries/records should be printed in a monospace font.
The records are technical, so having a monospace font there would fit it probably better.

Is this possible to change?

**Comment by tuxis-ie** [comment]
Feel free to write a patch for the menu. The menu is hardly used, so I don't see the use of investing time in it.

As for the fonts, that should be doable to make configurable.

**Comment by piwats** [comment]
Here is a quick and dirty patch:

```
--- base-orig.css       2015-04-17 15:51:08.022126000 +0200
+++ base.css    2015-04-17 15:56:24.412126000 +0200
@@ -11,21 +11,33 @@
 #wrap {
 }
 #menu {
-    width: 10%;
-    float: left;
-    border: 1px solid #DDD;
+    width: 100%;
+    border-bottom: 2px solid #DDD;
     font-family: 'Segoe UI Semilight','Open Sans',Verdana,Arial,Helvetica,sans-serif;
     font-weight: 300;
     font-size: 14px;
     line-height: 1.3;
+    display: inline-block;
+    margin-bottom: 5px;
+}
+
+#menu ul {
+    padding: 0;
+    margin: 0;
+}
+
+#menu ul li {
+    float: right;
+    margin-right: 5px;
 }
+
 #ImportZone {
     height: 0px;
     width: 0px;
 }
 .tables {
     float: right;
-    width: 89%;
+    width: 100%;
     min-width: 500px;
     margin-bottom: 5px;
 }
```

**Comment by tuxis-ie** [comment]
Welcome to github, where you can create PR's ;) :+1:

**Comment by piwats** [comment]
Sorry for the inconvenience - this will be the next step :)

**Comment by piwats** [comment]
That was easier as I expected - see pull request #44 .

**Comment by tuxis-ie** [comment]
Yeah, I personally don't like this. But, there nothing a css class and a configoption can't fix. Can you incorporate that in your PR?

**Comment by piwats** [comment]
What do you mean by a configoption?

something like:

in index.php:

```
<head>
    <title>NSEdit!</title>
    <link href="jquery-ui/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css"/>
    <link href="jtable/lib/themes/metro/blue/jtable.min.css" rel="stylesheet" type="text/css"/>
    <link href="css/base.css" rel="stylesheet" type="text/css"/>

 <?php if ($cssadditions === TRUE) { ?>
        <link href="css/additions.css" rel="stylesheet" type="text/css"/>
 <?php } ?>
```

together with $cssadditions = TREU; in config.inc.php?


    <script src="jquery-ui/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.core.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.widget.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.mouse.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.draggable.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.position.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.button.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.resizable.js" type="text/javascript"></script>
    <script src="jquery-ui/ui/jquery.ui.dialog.js" type="text/javascript"></script>
    <script src="jtable/lib/jquery.jtable.min.js" type="text/javascript"></script>
    <script src="js/addclear/addclear.js" type="text/javascript"></script>
</head>

**Comment by tuxis-ie** [comment]
Well, I wouldn't call it additions. But I'd say something like "$menutype = 'horizontal|vertical';" And add cssclasses to the appropriate elements.

**Comment by piwats** [comment]
Done, see my PR and Pull Req..

**Comment by tuxis-ie** [comment]
Closing with PR #44
