### ISSUE TITLE
Appearance of records of a zone

### ISSUE THREAD

**Issue by piwats** [tuxis-ie/nsedit#28]
When looking at records of a zone it would be very nice to be able to detach the main zone part from the record like this:

```
zone: test.com

subdns1.          test.com
subdns10.         test.com
subdns100.        test.com

```

Instead of 

```
zone: test.com

subdns1.test.com
subdns10.test.com
subdns100.test.com

```

This would give a more structural appearance to the list of records.

**Comment by tuxis-ie** [comment]
I personally like to see the whole record. @habbie showed me how pdnscontrol does it, they make the $ORIGIN part lightgrey. That can be a useful combi.
