### ISSUE TITLE
Every zone is listed 2 times

### ISSUE THREAD

**Issue by EugenMayer** [tuxis-ie/nsedit#36]
PDNS 3.4 + postgresql (8.4)

Every zone is listed 2 times. Creating a new zone using the UI als creates an 2 entriess. Deleting an entry deletes both entries - so its just a visualization bug, not really dupes in the backend

**Comment by tuxis-ie** [comment]
What happens if you request zones.php?action=list&jtStartIndex=0&jtPageSize=20 ? Do you see them double in there too?

**Comment by EugenMayer** [comment]
i see all zones 2 times .. checking http://127.0.0.1:8081/servers/localhost/zones | jq .. so directly on the pdns backend .. i see 12 zoens, not 6 .. so it seems a backend issue.

Sorry, i was confused...i though i checked that its correctly shown in the zones definition from the backend.

The bad thing..

pdnsng=# select count(id) from domains;
 count
-------
     6

So in the postgresql backend, i have exactly 6 zones (as expected) not 12 (dupes).
So, it seems to be an API issue from PDNS, not an nsedit issue, nor a data inconsistancy.

Every heard of this? Nevertheless, this should be a wont-fix - sorry!

**Comment by tuxis-ie** [comment]
Will you file an issue @pdns or should I?

**Comment by EugenMayer** [comment]
done already :) https://github.com/PowerDNS/pdns/issues/2366
