### ISSUE TITLE
bug: priority missing in "record create" request

### ISSUE THREAD

**Issue by EugenMayer** [tuxis-ie/nsedit#37]
pdns 3.4 / postgresql

The current pdwn schema requires a priority parameter - it should be at least part of the request priority:0 .. otherwise an API error will stop people for create records using the ui.

**Comment by tuxis-ie** [comment]
Hi,

It wasn't that easy removing the priority field. Is has been removed a few weeks ago. You (and me as well ;)) need to upgrade our nameservers.

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by EugenMayer** [comment]
Well at least, its still official: https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/ .. http://goo.gl/3ue0Cz .. not sure on which version you are currently focusing, but basically nobody will able to use your frontend right now

**Comment by tuxis-ie** [comment]
The documentation is behind. The current pdns version (3.4.2) does not support the priorityfield. One of the writers of the pdns api actually wrote the patch for nsedit to remove it.

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by EugenMayer** [comment]
wow .. you are fast moving.. :) Not sure if that is the right strategy though - i will have to remove nsedit in this case, since debians backport-repos have 3.4.1 

I undestand, that you dont want legacy code or maintain legacy features. Thanks

**Comment by tuxis-ie** [comment]
You can always get the latest pdns version from their website. If you're waiting for Debian you'd be able to use nsedit somewhere in 2035 ;) maybe @habbie can set up an actual working apt-get-able archive somewhere. 

On a serious note, the pdns API is highly experimental, as such, kinda so is the nsedit feature set. I'm hoping for maturity in pdns soon, but have little (or just no) influence on that.

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by EugenMayer** [comment]
Well no offense at all - i get your point. Iam basically writing a small ruby / httpparty cli to do what i actually need. NSedit will become read-only browsing for now
