### ISSUE TITLE
Theme should not hard code the urls to the fonts to http

### ISSUE THREAD

**Issue by darix** [tuxis-ie/nsedit#41]
Some browsers refuse to load http resources when the site is using https.

using "//hostname/path" makes sure the browser keeps using http or https for fetching resources depending on the current protocol.

fix:
```
perl -p -i -e 's|http://themes.googleusercontent.com|//themes.googleusercontent.com|g' $(grep -rl http://themes.googleusercontent.com .)
```

**Comment by fastcat** [comment]
Why not just always use HTTPS?

**Comment by tuxis-ie** [comment]
Closing as duplicate for #26

**Comment by HLFH** [comment]
Related to `jtable`. Fixed. https://github.com/hikalkan/jtable/issues/1434

**Comment by tuxis-ie** [comment]
You can 'fix' this by doing in the root of nsedit checkout:
```
cd jtable
git pull origin master
```

This will update you local jtable instance to the lastest version which includes https://github.com/hikalkan/jtable/pull/1888

I'll fix the version that nsedit ships in the submodule way (Just after I found out how to do that ;))
