### ISSUE TITLE
SOA timestamp not updated or incorrectly updated

### ISSUE THREAD

**Issue by harkx** [tuxis-ie/nsedit#42]
I have many zones that don't get an updated SOA timestamp after changing records. However, some do. I compared the zones, nothing fancy. (ns records, a cname for the www and that's it) All my zones are native.

I just created a new zone and it uses 20150409xx and increments this number, with 2 numbers everytime. (but today is 20150415) Time/date on the server are correct.

Is something wrong on my end or can someone confirm seeing this also?

![ns](https://cloud.githubusercontent.com/assets/7738282/7153603/0229117e-e34e-11e4-8727-689bee04a409.png)

**Comment by tuxis-ie** [comment]
The soa is updates by the API, not by nsedit. Look in your powerdns database for domain meta settings for something called soa-edit-API, iirc..

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by harkx** [comment]
Thanks for the quick reply and useful info. Now I know that nsedit has nothing to do with incrementing the SOA. :-)

I don't have any meta settings (but will look to be sure). I do notice there's a similar issue on the pdns github page, I will look at that and close this. (I'm using PowerDNS 3.4.3)

https://github.com/PowerDNS/pdns/issues/2377

**Comment by harkx** [comment]
But on the other hand, when I use my (ancient) poweradmin, that one does update the serial correctly. On every zone. Doing the same with nsedit (on zones that update correct in poweradmin) they don't get updated at all. :(

**Comment by tuxis-ie** [comment]
Yes, poweradmin does change the SOA. However, pdns requests that we let pdns change the SOA if required. 

nsedit sets the domainmetadata for newly added domains according to: https://doc.powerdns.com/md/authoritative/domainmetadata/

You might need to do that by hand for existing domains (soa_edit and soa_edit_api).

**Comment by harkx** [comment]
I added meta data for all the existing domains (like you suggested). Incrementing now works most of the time so I still suspect there's a bug in pdns somewhere.

However, when creating a new zone it always gets created with this timestamp: 2015040901

This is probably also pdns related?

**Comment by tuxis-ie** [comment]
Yes, nsedit does nothing with serials.



Met vriendelijke groeten,

-- 
Kerio Operator in de Cloud? https://www.kerioindecloud.nl/
Mark Schouten  | Tuxis Internet Engineering
KvK: 61527076 | http://www.tuxis.nl/
T: 0318 200208 | info@tuxis.nl



 Van:    Kristof Hardy <notifications@github.com> 
  Aan:    tuxis-ie/nsedit <nsedit@noreply.github.com> 
  Cc:    Tuxis Internet Engineering V.O.F. <mark@tuxis.nl> 
  Verzonden:    15-4-2015 11:59 
  Onderwerp:    Re: [nsedit] SOA timestamp not updated or incorrectly updated (#42) 


I added meta data for all the existing domains (like you suggested). Incrementing now works most of the time so I still suspect there's a bug in pdns somewhere. 
However, when creating a new zone it always gets created with this timestamp: 2015040901 
This is probably also pdns related?

**Comment by harkx** [comment]
Thanks! I'll look it up on pdns, sorry for the trouble :)
