### ISSUE TITLE
Extra nameservers (3 and 4) in default nameserver list

### ISSUE THREAD

**Issue by harkx** [tuxis-ie/nsedit#43]
It would be great to have the (optional..) possibility to have 2, 3 or 4 nameservers as default nameservers. (configurable via config file)

Currently this is limited to 2.

**Comment by bfbones** [comment]
See my PR #34 where I implemented exactly that. Hope the maintainer will merge this soon. As long as you can clone my repo to get this feature.

**Comment by extremeshok** [comment]
Please allow us to add multiple nameservers, ie.
ns1, ns2, ns3, ns4, ns5

Thanks

**Comment by tuxis-ie** [comment]
This is merged and functional.
