### ISSUE TITLE
API Error : 0 + Fix

### ISSUE THREAD

**Issue by firegore** [tuxis-ie/nsedit#45]
Greetings,

i tried installing NSedit today, it wasnt working because of this Error:

PHP message: PHP Notice:  Undefined variable: apiproto

You forgot to define in zones.php Line 14 that $apiproto must also be a Global, else it wont work ;)

Didnt know how to do a Pull Request so im just trying to help here

**Comment by tuxis-ie** [comment]
Good point! Thanks.
