### ISSUE TITLE
Changing record type results in duplicate entry

### ISSUE THREAD

**Issue by sid3windr** [tuxis-ie/nsedit#46]
Scenario:

banana.sid3windr.be CNAME apple.sid3windr.be

Click edit, select A in dropdown instead of CNAME, enter 127.0.0.1

Result:

banana.sid3windr.be CNAME apple.sid3windr.be
banana.sid3windr.be A 127.0.0.1

Expected result:

banana.sid3windr.be A 127.0.0.1

**Comment by tuxis-ie** [comment]
Yes, I've noticed this. Not sure if this is a pdns thing or a nsedit thing anymore.

**Comment by tuxis-ie** [comment]
If you can, please test the PR.

**Comment by sid3windr** [comment]
Just tested this, works for me!
