### ISSUE TITLE
deprecated class function called in php5.5

### ISSUE THREAD

**Issue by securelayers** [tuxis-ie/nsedit#50]
When trying to log in the portal we see the following error in the log file:

[:error] [pid 5767] [client x.x.x.x:54715] PHP Fatal error:  Call to a member function bindValue() on a non-object in /var/www/html/includes/misc.inc.php on line 111, referer: http://x.x.x.x/index.php

You should declare a function a a static function if you want to call it without an object.
Could you help us with this ?

Kind regards,

J.Prinse

**Comment by tuxis-ie** [comment]
Hi. I think you're missing php SQLite?

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by tuxis-ie** [comment]
Assuming this is fixed
