### ISSUE TITLE
Make it easy to add A and PTR records as a pair

### ISSUE THREAD

**Issue by fastcat** [tuxis-ie/nsedit#51]
Since A and PTR records are very often paired, it would be convenient to be able to add them as a pair.  Auto-detecting the PTR zone would be nifty, but not absolutely necessary.

Even cooler would be the ability to edit them as a pair, but that's rather more difficult.

**Comment by tuxis-ie** [comment]
That sounds like a good idea. Do you have any idea how you would like to see that implemented? It's not based on a zone, so it would be an extra option in a tools section in the menu or something like that?

**Comment by fastcat** [comment]
I see two "natural" ways to do it.

One: Make it an "extension" to the box for adding an A / AAAA record to a zone -- e.g. if you select one of those, have extra fields that appear for adding the PTR record.  The zone in which to place the PTR record could be a drop-down, with a little javascript to try to auto-select the correct zone based on the content for the A/AAAA record.  I don't think a separate TTL field would be necessary, use the same TTL for both records.

Two: A top level option as you suggest, with similar javascript to try to auto-select both zones.

The UI for option two is probably a bit cleaner, though it does require two variants of the zone auto-selector js.

As far as placement of the link, for option 1 it's embedded into the existing UI.  For option 2, I think the most natural placement would be another "tab" button alongside the import and add zone buttons.
