### ISSUE TITLE
Domain view should be sorted, and filterable

### ISSUE THREAD

**Issue by cmouse** [tuxis-ie/nsedit#52]
At the moment you cannot sort or filter the domains view. Similar functionality as datatables would be nice, but at least data should be sorted by name.

**Comment by tuxis-ie** [comment]
I've been looking into this. Filtering is already possible through search, so I don't know what you mean there. For sorting, the domains are sorted, but by tld first, and zone after..

**Comment by cmouse** [comment]
In-place filtering. Also some people prefer simple name based sorting.
