### ISSUE TITLE
nsedit: pdnssec rectify-zone/rectify-all-zones

### ISSUE THREAD

**Issue by piwats** [tuxis-ie/nsedit#54]
When having a zone in NSEC3 mode, adding a record to it without running pdnssec rectify-zone xxx or pdnssec rectify all zones results in NXDOMAIN response.

Is there a way nsedit could run pdnssec to rectify the zone it just "edited"?

**Comment by tuxis-ie** [comment]
According to https://doc.powerdns.com/md/httpapi/api_spec/#zones, this is not yet implemented. IMHO, pdns should always be responsible for this.

**Comment by piwats** [comment]
I meant, that when you deploy dnssec on pdns

1.) pdnssec secure-zone ZONE
2.) pdnssec set-nsec3 ZONE

after this, each time you add an additional record to the zone, you have to run pdnssec rectify-zone ZONE in order to get answers of the new records. If not, you'll get an NXDOMAIN response.

I'm not sure that this is an upstream bug.

But still, it would be nice to see, if nsedit could simply run pdnssec rectify-zone ZONE, so one doesn't need to run it manually.
