### ISSUE TITLE
Can't Aadd | Modify record. PowerDNS 3.4.1

### ISSUE THREAD

**Issue by vladsol** [tuxis-ie/nsedit#59]
PowerDNS version 3.4.1
When i tried to add or modify any (A, CNAME) record, i got an error: "API Error 422: Key 'priority' not an Integer or not present".

**Comment by tuxis-ie** [comment]
That is correct. The newer versions of powerdns do not use the priorityfield anymore. You should upgrade powerdns.

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by vladsol** [comment]
Thank you! :-)
