### ISSUE TITLE
OpenSSL module in PHP not mentioned in requirements

### ISSUE THREAD

**Issue by revellion** [tuxis-ie/nsedit#61]
I've noticed that OpenSSL module support in PHP is indeed a requirement for nsedit to work.

But it's not mentioned in the requirements. You might wanna add it, so someone else won't have to trip on that landmine that i did.

The init of the SQLite3  DB will throw a 500 the first run due to it trying to call openssl_random_pseudo_bytes(16). But it will not fail the DB transaction.

So the consequence is that the DB scheme is created but the admin/admin user is never inserted into the DB. 

Maybe a try() clause or so should be implemented to have it "fail" if the admin user cannot be created. Rather than silently fail.

Cheers .

**Comment by tuxis-ie** [comment]
Partially fixed in #69. The try should still be implemented.
