### ISSUE TITLE
Missing a closing bracket in misc.php

### ISSUE THREAD

**Issue by marzettimarco** [tuxis-ie/nsedit#65]
There's a trivial typo in includes/misc.inc.php .
Line 7 misses a closing bracket:
```
--- misc.inc.php.ORIG	2015-12-22 15:42:22.662075389 +0100
+++ misc.inc.php	2015-12-21 12:24:43.412742515 +0100
@@ -4,7 +4,7 @@
 
 $blocklogin = FALSE;
 
-if ((!isset($apipass) or empty($apipass)) or (!isset($apiip) or empty($apiip)) or (!isset($apiport) or empty($apiport)) or (!isset($apivers) or empty($apivers)) {
+if ((!isset($apipass) or empty($apipass)) or (!isset($apiip) or empty($apiip)) or (!isset($apiport) or empty($apiport)) or (!isset($apivers) or empty($apivers))) {
     $errormsg = 'You need to configure your settings for the PowerDNS API. See <a href="doc/apiconf.txt">doc/apiconf.txt</a>';
     $blocklogin = TRUE;
 }
```

Thank you

**Comment by job** [comment]
This patch gets rid of the PHP error, but I suspect there still is a bug in the logic.

**Comment by tuxis-ie** [comment]
I do see the error, I don't see where the logical error would be?

Mark Schouten

**Comment by job** [comment]
@tuxis-ie after adding the `)` the nsedit page kept asking me to configure access to the API, although I configured it. We can debug when you are back from vacation

**Comment by ruben-herold** [comment]
Hi I found the error:

empty also matches to "0" or 0:

    empty — Determine whether a variable is empty

In other words, it will return true if the variable is an empty string, false, array(), NULL, “0?, 0, and an unset variable. 


So I would fix ist this way:

-if ((!isset($apipass) or empty($apipass)) or (!isset($apiip) or empty($apiip)) or (!isset($apiport) or empty($apiport)) or (!isset($apivers) or empty($apivers)) {
+if ((!isset($apipass) or empty($apipass)) or (!isset($apiip) or empty($apiip)) or (!isset($apiport) or empty($apiport)) or (!isset($apivers) or is_null($apivers))) {
