### ISSUE TITLE
Problems adding dkim records

### ISSUE THREAD

**Issue by ruben-herold** [tuxis-ie/nsedit#66]
hi, 

I try to add an dkim entry with the webinterface. Seems some escaping went wrong:

default._domainkey.test descriptive text "'\"v=DKIM1\; k=rsa\; \"  \"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDndATEFTiqWfbASh5Uft8+sUDGwlSVudpng3dLwMtSkFPY7PGrOyHgidsS3NbATJaiv4tPP8m77yeatiOA67dtoAZ+2gUhhIEm7TYnJKGFIL8ByqBnO9zXLnK43LHMyN3w+9aXczIpB4uqSOmzB40ORQ0qSmjGLPI/XN+IVfkB5wIDAQAB\"'"

normal itlooks like:

default._domainkey.test descriptive text "v=DKIM1\; k=rsa\; " "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDndATEFTiqWfbASh5Uft8+sUDGwlSVudpng3dLwMtSkFPY7PGrOyHgidsS3NbATJaiv4tPP8m77yeatiOA67dtoAZ+2gUhhIEm7TYnJKGFIL8ByqBnO9zXLnK43LHMyN3w+9aXczIpB4uqSOmzB40ORQ0qSmjGLPI/XN+IVfkB5wIDAQAB"

**Comment by tuxis-ie** [comment]
If I'm not mistaking, the quotes in your 'normal' situation aren't required in nsedit. So you should try to use
```
v=DKIM1\; k=rsa\;  p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDndATEFTiqWfbASh5Uft8+sUDGwlSVudpng3dLwMtSkFPY7PGrOyHgidsS3NbATJaiv4tPP8m77yeatiOA67dtoAZ+2gUhhIEm7TYnJKGFIL8ByqBnO9zXLnK43LHMyN3w+9aXczIpB4uqSOmzB40ORQ0qSmjGLPI/XN+IVfkB5wIDAQAB
```

as input..

**Comment by ruben-herold** [comment]
Yes works if I send 

v=DKIM1; k=rsa;  p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDndATEFTiqWfbASh5Uft8+sUDGwlSVudpng3dLwMtSkFPY7PGrOyHgidsS3NbATJaiv4tPP8m77yeatiOA67dtoAZ+2gUhhIEm7TYnJKGFIL8ByqBnO9zXLnK43LHMyN3w+9aXczIpB4uqSOmzB40ORQ0qSmjGLPI/XN+IVfkB5wIDAQAB
