### ISSUE TITLE
Please add version control / logging changes to the admin

### ISSUE THREAD

**Issue by ruben-herold** [tuxis-ie/nsedit#67]
hi,

ich would be nice if we would have some kind of version control for the zone so that you can revoke changes and have a log who has changed the zone and what was changed.

**Comment by tuxis-ie** [comment]
The power of nsedit kindof is that there is virtually no local data. We could however keep a log in sqlite that logs the editing requests to the pdns API?

**Comment by ruben-herold** [comment]
Yes something like that.
