### ISSUE TITLE
unable to login to nsedit 

### ISSUE THREAD

**Issue by rpenugonda** [tuxis-ie/nsedit#7]
Hi installed nsedit and tried to login with admin/admin and never gets authenticated.

PHP Notice:  Use of undefined constant CSRF_TOKEN - assumed 'CSRF_TOKEN' in /home/rpenugonda/nsedit/index.php on line 125

Also i am able to see the user in the DB itself 
sqlite> select \* from users;
1|admin|$6$41f03d9acdc52ee6$nSYlWjbZ1MXO.9j//.Mz4RJTB.uS51k4FTlVzvsE3jFTFtncxKIdCKWlZcHJdkCv4Dhuzto9e7zdSD7CFM1u20|1

**Comment by Faizan200** [comment]
hi... i'm facing an error of api:0 some one guide me please to sort out this error as i'm running it on loaclhost.

**Comment by tuxis-ie** [comment]
@Faizan200 This is the third issue you polluted with your questions. Please open a new issue, in which you describe your issue. Stop clicking random issues and putting questions in it.
