### ISSUE TITLE
NSEDIT

### ISSUE THREAD

**Issue by mrlesmithjr** [tuxis-ie/nsedit#72]
Seeing the following errors after updating to latest code. Thoughts? At login screen you enter username/password and it just sits here. Below is what is in the apache error logs.

[Thu Jan 07 15:46:07.695556 2016] [:error] [pid 2093] [client 192.168.1.188:56247] PHP Notice:  Undefined variable: apivers in /var/www/html/nsedit/includes/misc.inc.php on line 12
[Thu Jan 07 15:46:07.695583 2016] [:error] [pid 2093] [client 192.168.1.188:56247] PHP Notice:  Undefined variable: apivers in /var/www/html/nsedit/includes/misc.inc.php on line 49
[Thu Jan 07 15:46:07.695671 2016] [:error] [pid 2093] [client 192.168.1.188:56247] PHP Notice:  Undefined variable: menutype in /var/www/html/nsedit/index.php on line 29
[Thu Jan 07 15:46:41.251464 2016] [:error] [pid 17692] [client 192.168.1.188:56255] PHP Warning:  include_once(includes/config.inc.php): failed to open stream: No such file or directory in /var/www/html/nsedit/index.php on line 3
[Thu Jan 07 15:46:41.251495 2016] [:error] [pid 17692] [client 192.168.1.188:56255] PHP Warning:  include_once(): Failed opening 'includes/config.inc.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/nsedit/index.php on line 3
[Thu Jan 07 15:46:41.251671 2016] [:error] [pid 17692] [client 192.168.1.188:56255] PHP Notice:  Undefined variable: apivers in /var/www/html/nsedit/includes/misc.inc.php on line 12
[Thu Jan 07 15:46:41.251719 2016] [:error] [pid 17692] [client 192.168.1.188:56255] PHP Notice:  Undefined variable: apivers in /var/www/html/nsedit/includes/misc.inc.php on line 49
[Thu Jan 07 15:46:41.251814 2016] [:error] [pid 17692] [client 192.168.1.188:56255] PHP Notice:  Undefined variable: menutype in /var/www/html/nsedit/index.php on line 29

**Comment by ruben-herold** [comment]
what is in your misc.inc.php and in your config.inc.php

**Comment by tuxis-ie** [comment]
The latest code includes apivers for 4.0 compatibility. There should be a better check for that, apparently.

**Comment by tuxis-ie** [comment]
Reading back, you should see a notice in the web interface with a link to documentation about it? Login should be blocked..

**Comment by mrlesmithjr** [comment]
We were able to restore back to a current version and it is working again.
But I will look through and see if I can figure out what happened. One
thing I did notice as well was/is config.inc.php prior to the latest code
was working with it being in root of nsedit instead of includes/ but it
would not work with the current version so a symlink was created within
includes/ but still a no go. I will dig deeper as I am very confused now
how it was ever working before :)
I use Ansible for all of my deployments and have done these 100's of times
w/out any issues but s--t happens right? :)
https://github.com/mrlesmithjr/ansible-powerdns

And here are the tasks within the Ansible role with the configuration of
nsedit at the bottom. Last updated in November and things seemed to still
work.

https://github.com/mrlesmithjr/ansible-powerdns/blob/master/tasks/debian_pdns_server.yml

Appreciate the follow up. And I will be in touch soon after I dig a little
deeper.

On Thu, Jan 7, 2016 at 4:44 PM, Tuxis Internet Engineering V.O.F. <
notifications@github.com> wrote:

> Reading back, you should see a notice in the web interface with a link to
> documentation about it? Login should be blocked..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuxis-ie/nsedit/issues/72#issuecomment-169815476>.
>



-- 
Twitter @mrlesmithjr <http://twitter.com/mrlesmithjr>
Blog EverythingShouldBeVirtual.com
Interested in blog sponsorship? Go to http://bit.ly/10Aj7Sq

**Comment by mrlesmithjr** [comment]
So another thing could be the Ansible template I am using to configure config.inc.php is out of date for the new code.
Here is the link to the Ansible template

https://raw.githubusercontent.com/mrlesmithjr/ansible-powerdns/master/templates/nsedit.config.inc.php.j2

**Comment by tuxis-ie** [comment]
It probably is. Try comparing it with the master version. Cool to see people really deploying nsedit!

**Comment by mrlesmithjr** [comment]
Yeah I see some differences already. So I will spin up a vagrant box and do
some testing. Yeah nsedit is useful for those that want a webUI for
PowerDNS. I myself very seldom use the WebUI and just do API calls using
Ansible.

You may be interested in the link below on backing up and recovering :)

http://everythingshouldbevirtual.com/ansible-discover-and-backup-powerdns-zonesrecords

On Thu, Jan 7, 2016 at 5:00 PM, Tuxis Internet Engineering V.O.F. <
notifications@github.com> wrote:

> It probably is. Try comparing it with the master version. Cool to see
> people really deploying nsedit!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuxis-ie/nsedit/issues/72#issuecomment-169819828>.
>



-- 
Twitter @mrlesmithjr <http://twitter.com/mrlesmithjr>
Blog EverythingShouldBeVirtual.com
Interested in blog sponsorship? Go to http://bit.ly/10Aj7Sq

**Comment by tuxis-ie** [comment]
Cool. You know the API can do export and import in plaintext bind-style as well?

**Comment by mrlesmithjr** [comment]
Have not tried that yet.

**Comment by mrlesmithjr** [comment]
OK. Issue resolved. This was all on me...With the minor changes to the config.inc.php file between what I originally used as a template and the new config.inc.php-dist all is good. Below is the diff of the two templates just as an FYI. I have also include a Vagrant DDI setup in the link below if anyone is interested in testing this all out that I made several months ago for training others.

nsedit-config.inc.php.j2  (New)
nsedit.config.inc.php.j2  (Old)
vagrant@ddi:/etc/ansible/roles/ansible-powerdns/templates$ diff nsedit-config.inc.php.j2 nsedit.config.inc.php.j2 
5c5
< $apiip   = '';           # The IP of the PowerDNS API
---
> $apiip   = 'localhost';           # The IP of the PowerDNS API
7d6
< $apivers = 0;            # The version of the PowerDNS API. 0 == experimental, 1 = v1 (pdns 4.0)
54,60c53,55
< $defaults['ns'][0] = 'unconfigured.primaryns';          # The value of the first NS-record
< $defaults['ns'][1] = 'unconfigured.secondaryns';        # The value of the second NS-record
< $defaults['ttl']   = 3600;                              # Default TTL for records
< 
< ## UI Options
< $menutype = 'horizontal'; # horizontal|vertical - use a horizontal or vertical menu
< $logo = 'https://www.tuxis.nl/uploads/images/nsedit.png';
---
> $defaults['primaryns']   = 'unconfigured.primaryns';    # The value of the first NS-record
> $defaults['secondaryns'] = 'unconfigured.secondaryns';  # The value of the second NS-record
> $defaults['ttl']         = 3600;
 


https://github.com/mrlesmithjr/vagrant-ansible-ddi
