### ISSUE TITLE
star entry

### ISSUE THREAD

**Issue by celevra** [tuxis-ie/nsedit#77]
Hi,

how can i create a star entry? like
*.example.net. A 127.0.0.1

i get a 
API Error 422: Label '*.example.net.' contains unsupported characters

**Comment by tuxis-ie** [comment]
Hmm, odd. That works fine for me..

**Comment by celevra** [comment]
I'm in the newest pdns 4 Version. I've also openend a bug in pdns git repository, they've fixed it, so no nsedit bug, thank you

https://github.com/PowerDNS/pdns/issues/3406#event-557737517

**Comment by tuxis-ie** [comment]
Thanks for the feedback. :)
