### ISSUE TITLE
Allow to disable records

### ISSUE THREAD

**Issue by nickygerritsen** [tuxis-ie/nsedit#78]
First of all, great product. I really enjoy it and its simplicity.

However, would it be possible to add the option to disable a record? As far as I know this would only mean we need to set "disabled: true" when sending it to the API.

The biggest problem I currently see is that we use the whole JSON as ID for the record and that might mean the ID changes when we disable it, but maybe I'm wrong in that sense?

Disabling records would make sense for us as we sometimes want to temporarily not serve some records.

If the ID thing is not a problem, I think I might even easily be able to provide a PR and am willing to do that :).

**Comment by tuxis-ie** [comment]
I don't think there would be an issue. Feel free to fix a pr and I'd be happy to merge it.

**Comment by tuxis-ie** [comment]
Merged
