### ISSUE TITLE
Hardcoded HTTP font references instead of //

### ISSUE THREAD

**Issue by HansVanEijsden** [tuxis-ie/nsedit#79]
Thanks for NSEdit!
Some small problems with HTTPS though: mixed content warnings when accessing via HTTPS.

In the theme files in jtable/lib/themes/metro/*/*.css, references for example go to http://themes.googleusercontent.com/static/fonts/opensans/v6/DXI1ORHCpsQm3Vp6mXoaTRa1RVmPjeKy21_GQJaLlJI.woff but removing http: makes them also work on https domains.
Can you please change them to // instead of http://?

**Comment by tuxis-ie** [comment]
Jo,

Sorry, this is not an issue in nsedit but in the jquery library we include. There is a bug open somewhere upstream...

**Comment by tuxis-ie** [comment]
But! I see that that is fixed upstream, so now I just have to test a new upstream version. Can be fixed today, I think.

**Comment by tuxis-ie** [comment]
You can 'fix' this by doing in the root of nsedit checkout:
```
cd jtable
git pull origin master
```

This will update you local jtable instance to the lastest version which includes https://github.com/hikalkan/jtable/pull/1888

I'll fix the version that nsedit ships in the submodule way (Just after I found out how to do that ;))
