### ISSUE TITLE
Browser complains about unsecure code if hosted on https

### ISSUE THREAD

**Issue by ruben-herold** [tuxis-ie/nsedit#88]
hi,

If I try to access my nsedit installation all my browser sends me warnings about unsecure code.
Seems that there are some hard coded http:// sources.

for example the google font's are included via http

**Comment by tuxis-ie** [comment]
https://github.com/tuxis-ie/nsedit/issues/79

You should update the jtable submodule.

**Comment by ruben-herold** [comment]
thx that does the trick
