### ISSUE TITLE
Nesedit stopped working 

### ISSUE THREAD

**Issue by ruben-herold** [tuxis-ie/nsedit#89]
hi

with current git I can only change the password or go to logout. All other buttons don't work. My browser don't even try to send an request.

**Comment by tuxis-ie** [comment]
What did you change?

**Comment by ruben-herold** [comment]
only the config but this was long time ago:

[root@dns nsedit]# git pull
Already up-to-date.
[root@dns nsedit]#

**Comment by tuxis-ie** [comment]
So nobody changed anything, and it just stopped working? And yet you just created a ticket about HTTPS and upgraded jtable..

I need a bit more info.

**Comment by ruben-herold** [comment]
Also I have now tried:

mv nsedit nsdedit.old
git clone --recursive https://github.com/tuxis-ie/nsedit.git
cd nsedit/jtable
git pull origin master
cd ..
cp ../nsedit.old/includes/config.inc.php  includes/
cp ../nsedit.old/includes/misc.inc.php includes/

Same problem in different browsers
Theonly things I changed in the last weeks are regular browser updates

**Comment by tuxis-ie** [comment]
Ok. What does your browsers firebug/developer-console say?

On Mon, 2016-05-09 at 05:07 -0700, Ruben Herold wrote:
> Also I have now tried:
> mv nsedit nsdedit.old
> git clone --recursive https://github.com/tuxis-ie/nsedit.git
> cd nsedit/jtable
> git pull origin master
> cd ..
> cp ../nsedit.old/includes/config.inc.php includes/
> cp ../nsedit.old/includes/misc.inc.php includes/
> Same problem in different browsers
> Theonly things I changed in the last weeks are regular browser
> updates
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
-- 
Kerio Operator in de Cloud? https://www.kerioindecloud.nl/
Mark Schouten  | Tuxis Internet Engineering
KvK: 61527076  | http://www.tuxis.nl/
T: 0318 200208 | info@tuxis.nl

**Comment by ruben-herold** [comment]
SyntaxError: unterminated string literal

defaultValue: '<br />

	
index.php# (Zeile 543, Spalte 54)

**Comment by tuxis-ie** [comment]
What does your config say about $defaults['defaulttype'] ?


On Mon, 2016-05-09 at 05:21 -0700, Ruben Herold wrote:
> SyntaxError: unterminated string literal
> defaultValue: '
> index.php# (Zeile 543, Spalte 54)
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
-- 
Kerio Operator in de Cloud? https://www.kerioindecloud.nl/
Mark Schouten  | Tuxis Internet Engineering
KvK: 61527076  | http://www.tuxis.nl/
T: 0318 200208 | info@tuxis.nl

**Comment by ruben-herold** [comment]
The setting $defaults['disabled'] = false;     # Default disabled state was missing in my config file. 
After adding the setting to the config it works.
