### ISSUE TITLE
Need a way to search a zone for records

### ISSUE THREAD

**Issue by bbusschots-mu** [tuxis-ie/nsedit#90]
I'm trying to manage a zone with over 8,000 records, and I can't seem to see any way of searching or filtering the records.

Unless I'm missing something obvious, it seems that NSEdit is utterly impractical for managing large zones.

**Comment by tuxis-ie** [comment]
I've looked into this, but haven't found a good solution yet. But, since v1.0, NSEdit does support sorting, which should make it a bit better..
