### ISSUE TITLE
API Error 404: Not Found

### ISSUE THREAD

**Issue by emilstahl** [tuxis-ie/nsedit#93]
I'm getting this error.

`API Error 404: Not Found`

How can I  debug?

**Comment by tuxis-ie** [comment]
Probably by setting the correct api path values?

**Comment by emilstahl** [comment]
@tuxis-ie I don't see anything about paths in the config? I entered the correct IP and API version.

**Comment by tuxis-ie** [comment]
Which version are you running? Are you running a simple setup? Can you reach the Api manually?

**Comment by emilstahl** [comment]
@tuxis-ie I set `$apisid  =` to the server-id configured in pdns.conf

I just tried changing it back to localhost and it works. 👍

**Comment by emilstahl** [comment]
I can see the zones now, however when I click on the records icon, I get the 404 error.

**Comment by mschirrmeister** [comment]
I am seeing the same error when I try to click the records button for a zone.
Yes, I can call the api manually just fine.

I set `$apivers` to **1**.
I looked at the actual URI that it uses when I get the error and the code is constructing a wrong URI. The URI looks something like this `/api/v1api/v1/servers/....`.
So it is appending `api/v1` somewhere in the code. I was not able to figure out where it is doing this. But I think this is the problem.

**Comment by tuxis-ie** [comment]
Which version of pdns?

**Comment by mschirrmeister** [comment]
4.0.0 from https://repo.powerdns.com/centos/x86_64/7/auth-40/

**Comment by tuxis-ie** [comment]
There is some (or a lot?) of work todo to support 4.0 like we should. I didn't have time nor need to do so, and now I just don't have the time.

So help is appreciated in improving nsedit.

**Comment by luckyraul** [comment]
I have only notices prefix ```api/v1/``` beetween old and new urls. So It can be not such a trouble

**Comment by tuxis-ie** [comment]
No. They changed a lot more. Including the fact that records are no longer rrsets, but part of rrsets.

Anyway, I'm working on v1.0 for nsedit, making it ready for 4.0 and prettier to use and read the code.

**Comment by luckyraul** [comment]
@tuxis-ie  Do you have a approximate schedule for this release ?

**Comment by tuxis-ie** [comment]
I'm working on it, and it starts looking like something. See https://github.com/tuxis-ie/nsedit/tree/pdns-40

**Comment by tuxis-ie** [comment]
This should be #73. Closing this one, keeping #73 in the loop.

**Comment by tuxis-ie** [comment]
Please note: https://github.com/tuxis-ie/nsedit/releases/tag/v1.0
