### ISSUE TITLE
v1.0 404 error on ubuntu 16.04

### ISSUE THREAD

**Issue by abcdmitry** [tuxis-ie/nsedit#95]
Just a note for ubuntu 16.04 users:

pdns from standard ubuntu repository has version 4.0.0-alpha2 which doesn't support api version discovery used by new nsedit.

Ubuntu users has to upgrade following instructions from https://repo.powerdns.com/

**Comment by tuxis-ie** [comment]
Can you create a pr with an updated version of README.md?

**Comment by abcdmitry** [comment]
Sure, I'll do it later today

**Comment by tuxis-ie** [comment]
That's merged. I also updated the 'Release' page. Thanks!
