### ISSUE TITLE
Add User doesn't work

### ISSUE THREAD

**Issue by petzsch** [tuxis-ie/nsedit#97]
![screen_add_new_user](https://cloud.githubusercontent.com/assets/1374810/17465428/01444d18-5cf7-11e6-82b2-af21a01fd7ab.png)
As admin I can't add more users. The input box for the username is missing. I'm on 1.0

**Comment by tuxis-ie** [comment]
Oh crap.... http://jtable.org/ApiReference/FieldOptions#fopt-key seems to be the issue here.

Quick fix is to set create: true in the #Users table for username.

I'll fix it permanently tomorrow morning.
