### ISSUE TITLE
Modify record ttl won't work

### ISSUE THREAD

**Issue by petzsch** [tuxis-ie/nsedit#99]
Hi. I just updatd to the current master. The user issue I reported is fixed. However I can't seem to modify a records ttl. I already lowerd the minTTL in the SOA record, it doesn't help. My change just gets ignored. (ttl of the SOA record for instance)

**Comment by petzsch** [comment]
Just applied the patch. Only the Record that i changed, got the new TTL. Works as I would expect it. :+1:

**Comment by tuxis-ie** [comment]
The whole rrset will get the new ttl (a record in pdns does not have a ttl, the rrset does). However, when you save the record, I'm unable to let jtable refresh more than one row in the table. So only the record you changed shows the new ttl. When you refresh the records-table, you should find that the whole rrset is changed (if there are multiple records within the rrset).

Thanks for reporting and checking!
